"""empty message

Revision ID: 273e9ea40df6
Revises: 
Create Date: 2021-04-05 22:28:53.690538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273e9ea40df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
